"""Curated skill keyword list for the library resume parser.

Lowercased, unique, sorted. ~200 entries covering languages, frameworks,
data stores, cloud, infra, tooling, ML/AI. Extend liberally; the parser
does case-insensitive substring containment, so spelling variants
(e.g. "node.js" vs "nodejs") should both be listed where common.

# TODO(P3-llm-parser): Replace substring containment with word-boundary
# detection (regex \\b…\\b or tokenization) to eliminate false positives
# from short tokens (e.g. single chars, common substrings in framework names).
"""

from __future__ import annotations

from typing import Final

SKILLS: Final[tuple[str, ...]] = (
    # --- Languages ---
    "bash",
    "c#",
    "c++",
    "clojure",
    "css",
    "dart",
    "elixir",
    "erlang",
    "golang",
    "groovy",
    "haskell",
    "html",
    "java",
    "javascript",
    "julia",
    "kotlin",
    "lua",
    "matlab",
    "objective-c",
    "ocaml",
    "perl",
    "php",
    "powershell",
    "python",
    "ruby",
    "rust",
    "scala",
    "shell",
    "sql",
    "swift",
    "typescript",
    "vb.net",
    "zsh",
    # --- Web frameworks (backend) ---
    "asp.net",
    "django",
    "express",
    "fastapi",
    "flask",
    "gin",
    "koa",
    "laravel",
    "nestjs",
    "node.js",
    "nodejs",
    "phoenix",
    "rails",
    "spring",
    "spring boot",
    "tornado",
    # --- Web frameworks (frontend) ---
    "angular",
    "ember",
    "next.js",
    "nextjs",
    "nuxt",
    "react",
    "react native",
    "redux",
    "remix",
    "solid.js",
    "svelte",
    "tailwind",
    "vite",
    "vue",
    "vue.js",
    "webpack",
    # --- Mobile ---
    "android",
    "flutter",
    "ios",
    "jetpack compose",
    "swiftui",
    "xamarin",
    # --- Data / DBs ---
    "bigquery",
    "cassandra",
    "clickhouse",
    "cockroachdb",
    "couchbase",
    "dynamodb",
    "elasticsearch",
    "hbase",
    "kafka",
    "mariadb",
    "mongodb",
    "mssql",
    "mysql",
    "neo4j",
    "opensearch",
    "oracle",
    "pgvector",
    "postgres",
    "postgresql",
    "rabbitmq",
    "redis",
    "redshift",
    "snowflake",
    "spark",
    "sqlite",
    "trino",
    # --- Cloud ---
    "aws",
    "azure",
    "cloudflare",
    "digitalocean",
    "fly.io",
    "gcp",
    "google cloud",
    "heroku",
    "linode",
    "render",
    "vercel",
    # --- Infra / DevOps ---
    "ansible",
    "argocd",
    "circleci",
    "docker",
    "elk",
    "fluent bit",
    "github actions",
    "gitlab ci",
    "grafana",
    "helm",
    "istio",
    "jenkins",
    "kubernetes",
    "linkerd",
    "loki",
    "nginx",
    "opentelemetry",
    "packer",
    "prometheus",
    "puppet",
    "saltstack",
    "tempo",
    "terraform",
    "vault",
    # --- API / messaging ---
    "graphql",
    "grpc",
    "openapi",
    "rest",
    "soap",
    "websocket",
    # --- Auth / security ---
    "jwt",
    "oauth",
    "oauth2",
    "oidc",
    "saml",
    # --- ML / AI ---
    "huggingface",
    "keras",
    "langchain",
    "llamaindex",
    "mlflow",
    "numpy",
    "pandas",
    "pytorch",
    "scikit-learn",
    "spacy",
    "tensorflow",
    "transformers",
    "xgboost",
    # --- Testing ---
    "cypress",
    "jest",
    "junit",
    "mocha",
    "playwright",
    "pytest",
    "selenium",
    "testng",
    "vitest",
    # --- ORMs / clients ---
    "alembic",
    "django orm",
    "hibernate",
    "jdbi",
    "knex",
    "prisma",
    "sequelize",
    "sqlalchemy",
    "typeorm",
    # --- Methodologies / other ---
    "agile",
    "ci/cd",
    "ddd",
    "event sourcing",
    "kanban",
    "microservices",
    "scrum",
    "tdd",
    "uml",
)
